AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
